version: '0.0.1'  # This is a static version, not using the env variable

services:
  mongodb_primary:
    image: mongo:${mongoDB_version}
    container_name: mongodb_primary
    ports:
      - "27017:27017"
    networks:
      - mongoCluster_Primary_to_1
      - mongoCluster_Primary_to_2
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1

  mongodb_secondary_1:
    image: mongo:${mongoDB_version}
    container_name: mongodb_secondary_1
    ports:
      - "27018:27017"
    depends_on:
      - mongodb_primary
    networks:
      - mongoCluster_Primary_to_1

  mongodb_secondary_2:
    image: mongo:${mongoDB_version}
    container_name: mongodb_secondary_2
    ports:
      - "27019:27017"
    depends_on:
      - mongodb_secondary_1
    networks:
      - mongoCluster_Primary_to_2
    command: >
      docker exec mongodb_primary mongo --eval "rs.initiate({
        _id: 'myReplicaSet',
        members: [
          { _id: 0, host: 'mongodb_primary:27017' },
          { _id: 1, host: 'mongodb_secondary_1:27017' },
          { _id: 2, host: 'mongodb_secondary_2:27017' }
        ]
      })"

networks:
  mongoCluster_Primary_to_1:
    name: Primarymongo_to_1
    driver: bridge
  mongoCluster_Primary_to_2:
    name: Primarymongo_to_2
    driver: bridge