version: '1'  # This is a static version, not using the env variable

services:
  mongodb_primary:
    image: ${mongodb_image}
    container_name: ${mongo_primary_container_name}
    ports:
      - "27017:27017"
    volumes:
       - mongodb_primary_volume:/data/db
    networks:
      - mongodb_replica_set
      - mongodb_primary_to_yolo
    command: mongod --replSet myReplicaSet --bind_ip_all

  mongodb_secondary_1:
    image: ${mongodb_image}
    container_name: ${mongo_secondary_1_container_name}
    ports:
      - "27018:27017"
    volumes:
      - mongodb_secondary_1_volume:/data/db
    networks:
      - mongodb_replica_set
    command: mongod --replSet myReplicaSet --bind_ip_all

  mongodb_secondary_2:
    image: ${mongodb_image}
    container_name: ${mongo_secondary_2_container_name}
    ports:
      - "27019:27017"
    volumes:
      - mongodb_secondary_2_volume:/data/db
    networks:
      - mongodb_replica_set
    command: mongod --replSet myReplicaSet --bind_ip_all


  replica_initializer:
    image: ${replica_initializer_image}
    container_name: ${replica_initializer_name}
    depends_on:
      - mongodb_primary
      - mongodb_secondary_1
      - mongodb_secondary_2
    networks:
      - mongodb_replica_set
    env_file:
      - .env


  yolo5_app:
    image: ${yolo5_image}
    container_name: ${yolo_container_name}
    ports:
      - "8081:8081"
    depends_on:
      - replica_initializer
    stdin_open: true
    tty: true
    networks:
      - mongodb_primary_to_yolo
      - yolo_to_polybot
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
    environment:
      - MONGO_HOST=mongodb_primary
      - MONGO_PORT=27017
    env_file:
      - .env


  polybot_app:
    image: ${polybot_image}
    container_name: polybot_app
    depends_on:
      - replica_initializer
    networks:
      - yolo_to_polybot
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
    ports:
      - "8443:8443"
    env_file:
      - .env


networks:
  mongodb_replica_set:
    name: ${mongodb_replica_set}
    driver: ${driver}
  mongodb_primary_to_yolo:
    name: ${mongodb_primary_to_yolo}
    driver: ${driver}
  yolo_to_polybot:
    name: ${yolo_to_polybot}
    driver: ${driver}

volumes:
  mongodb_primary_volume:
  mongodb_secondary_1_volume:
  mongodb_secondary_2_volume:
